### ISSUE TITLE
안녕하세요? 프레임웍 설치 질문이 있어서요ㅠㅠ

### ISSUE THREAD

**Issue by misgradu** [gshn/cpfs#1]
안녕하세요? 혹시 저 기억하실 지 모르겠네요..
3년전 쯤 뵜었던 것 같아요.. 저는 글로벌셀러창업연구소 직원이었구요. 그때 회사에 면접보러 오셨다가 장성호팀장님과 김민섭 팀장님이랑 같이 한 번 저녁식사 같이 한 적이 있었는데.. 기억나실 지 모르겠어요.. 
다름이 아니고 그누보드에서도 공개하셨었는데 프레임웍을 한 번 써보고 싶어서요.. 어제 작업해보다가 좀 막히는 부분이 있는데 도저히 어떻게 해야할 지 몰라서 이렇게 글 남깁니다.
nginx로 서버 운영하고 있는데 index.php를  제거할 수 있도록 설정하려면 무엇을 어떻게 해야할 지 모르겠어요..
현재 디렉토리 구조는 /www밑에 /public 과 /src 디렉토리를 생성했구요.. nginx에서 root 디렉토리를 /www/public으로 설정을 해둔 상태입니다. 
설치후 사이트 url로 접근하면 /public/index.php로 접근하기는 하는 것 같아요.. 그런데 다른 페이지들 /login, /notice, /install 등은 접근이 아예 안되고 있네요.. 
바쁘시겠지만 간단하게라도 힌트를 주시면 해보겠습니다. 꼭 써보고 싶어요ㅠㅠ

**Comment by gshn** [comment]
아 안녕하세요! 석호님
이 소스가 완성된 형태는 아니라서 사용하시기 불편하실거 같은데 ^^;
일단 nginx의 설정은 아래의 사이트에서 참고 하시면 됩니다.

https://www.digitalocean.com/community/tools/nginx#?

cpfs는 테이블의 name과 comment 부분을 많이 참조합니다. 그게 정확히 작성되어 있을 때만 제대로 작동합니다.
관리자 페이지를 만들 때 반복적으로 코드를 작성해야하는 부분을 테이블 스키마에서 모두 자동으로 생성하는 형태입니다.
쓰기, 수정 페이지의 뷰단 코드도 컨트롤 단에서 스키마를 참조해 던져주면 자동으로 생성되길 원해서 만든 거였습니다.
저 개인적으로는 쉽게 사용할 수 있는데 다른 분들이 구조를 파악하려면 시간이 소요될 것으로 보여요.
그리고 지금은 저도 쓰지 않아서 코드를 추가하거나 수정할 계획은 없습니다.
작업 의뢰가 와서 빠른시간 안에 어드민페이지가 필요할 때만 쓰고 있습니다.
참고 하시기 바랍니다!

**Comment by misgradu** [comment]
네 감사합니다. 
어찌저찌 사이트는 잘 띄웠구요.. 
소스도 찬찬히 분석하면서 보고 있습니다.
감사해요~~
